7 feature 7 home screen
CSC207-2022F-UofT/course-project-tripledotstudios pull request #27
Opened 2022-11-25 03:06 UTC by yeludan

2022-11-25 22:46 UTC, ggykwong commented
Gwen reviews:
- [ ] CreateAccountOrLogin
- [ ] EnterAGameScreen
- [ ] LoginScreen
- [ ] RegisterScreen
- [ ] LoginInteractor
- [ ] Controller
- [ ] Presenter

Josh reviews:
- [ ] ExitOptionsScreen
- [ ] StorylineInterface
- [ ] Controller
- [ ] Presenter

2022-11-28 21:46 UTC, ggykwong commented
RegisterScreen and LoginScreen have correct usage of LoginController, which correctly uses LoginInteractor, and StorylineController to access StorylineInteractor's soundSwitch method.

2022-11-28 21:50 UTC, ggykwong commented
CreateAccountOrLogin looks good. StorylineInteractor will need to be constructed before CreateAccountOrLogin is in the main program.

2022-11-28 21:59 UTC, ggykwong commented
EnterAGameScreen has correct usage of LoginController and StorylineController. LoginController also correctly uses LoginInteractor.

2022-11-28 22:21 UTC, jshchn4 commented on src/main/java/presenter/StorylinePresenter.java
> +    public void display_event_choices(String narrationChoices) { //display choices string narration
List<String> narrationChoices

2022-11-28 22:22 UTC, ggykwong commented
LoginPresenter complies with LoginInterface and LoginInteractor's createAccount and validateLogin methods.

For ExitOptionsScreen--exitGame brings you to the CreateAccountOrLogin UI. Should the user assume that exiting the game automatically logs them out as well? If so, exitGame may also have to initiate the log out process. If the user isn't automatically logged out, they should be brought to the EnterAGameScreen UI instead.

Otherwise, all of the files I have reviewed look good!

2022-11-28 22:24 UTC, jshchn4 requested changes

2022-11-28 22:24 UTC, jshchn4 commented on src/main/java/controller/StorylineController.java
> +    public void updateEventID(Player player, String narrationChoices) {
int choice

2022-11-28 22:24 UTC, jshchn4 commented on src/main/java/presenter/StorylinePresenter.java
> +    public void display_event_choices(String narrationChoices) { //display choices string narration
List<String> narrationChoices

2022-11-28 22:24 UTC, jshchn4 commented on src/main/java/controller/StorylineController.java
> +        storylineInteractor.updateEventID(player, narrationChoices);
updateEventID(player, choice)

2022-11-28 22:26 UTC, ggykwong requested changes
LoginPresenter complies with LoginInterface and LoginInteractor's createAccount and validateLogin methods.

For ExitOptionsScreen--exitGame brings you to the CreateAccountOrLogin UI. Should the user assume that exiting the game automatically logs them out as well? If so, exitGame has to initiate the log out process. If the user isn't automatically logged out, they should be brought to the EnterAGameScreen UI instead.

Otherwise, all of the files I have reviewed look good!

2022-11-28 22:56 UTC, merged

2022-11-28 22:57 UTC, yeludan commented on src/main/java/controller/StorylineController.java
> +    public void updateEventID(Player player, String narrationChoices) {
fixed!